### ISSUE TITLE
highlight tests with fewer than 2 passing implementations

### ISSUE THREAD

**Issue by aljones15** [digitalbazaar/mocha-w3c-interop-reporter#46]

**Comment by BigBlueHat** [comment]
Highlighting them in place is fine, but the more helpful thing would be a summary listing the test names (with links to those lines in the reporter). Ultimately, we need to know the specific tests that have insufficient passing implementations--ideally without having to scroll through the whole report to find them.

**Comment by aljones15** [comment]
closing as this has been addressed
